~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This is a prognostic field. That is, it is a type of primary
field that gets updated by the calculations performed
during an integration. It must reside in D1 and the dump
and be registered primarily in section 0. 

The prognostic can be treated as a diagnostic if it is available
and so can be output to PP files (standard and mean PP files).

%I gen_primary
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
