This is one of a series of windows that allows users to specify which version of
a particular section they want to run with.

The unified model is split into sections which are collections of routines that
perform a task. These sections are also used in the STASH diagnostic system to
define the code that produces a diagnostic. See UM Basic Users Guide on sections
releases and frozen versions.
 
The sections in this series of windows defines the scientific routines used in
the atmospheric model. 

Some sections allow the user to choose from more than 1 version of that section,
each version (or more strictly version<release>) is defined by an identifier
such as <1A>.
Different configurations of the model use different versions and users should
look at standard experiments to see what they should be defining. Information in
the help windows may be out of date.
