
The UM functionality relating to this panel is not yet available
although the UMUI functionality more or less works. So please do not
use without further advice.

It is the intention that metadata describing available ancillary
fields and files will be kept in record files similar to STASHmaster
record files. The UMUI already maintains such record files but the UM
is not set up to read them. The following help is therefore not yet
relevant.

----

This panel lists the user supplied ancillary file and field records
obtained from the files listed in the preceding panel in two separate
tables. Additional information is required to fully define the use of
the items. If there are no user supplied items for fields or files or
both, then the relevant table or tables will not appear.

The listed files are read on moving from the preceding panel to this
panel. If there were errors or warnings, they are displayed in a
separate window. Warnings may not be important, but if there were
errors in any of the file types, the table relating to the file type
will not appear and an error message will appear in its place.

Warnings are given when an item in the user supplied file overwrites
an item in the centrally held files. Note that the setup for such
items supplied here (such as file names or updating frequencies) will
override the setup supplied in the original ancillary windows
elsewhere in the UMUI.
