Generalised suite variables (in RED).
   If the user specifies they are using external control
   via the Suite Control System (SCS), some UMUI variables
   can be set to the value EXTERNAL. Such variables and
   their questions, appear in RED on the screen.
   If you specify EXTERNAL, the actual value used by the UM
   will be taken from an externally set environment variable
   as defined through the SCSUI.
   Both climate integrations and one-off integrations will
   not, typically, use the SCS.
   You can specify whether or not to use external control
   via the panel subindep_ExternalCntrl.
