Absorption by a number of trace gases may be included in the calculation,
provided that appropriate spectral data are contained in the spectral
file. Note that spectral files cannot be checked in the UMUI and users
should consult the supporting documentation to select a spectral file
containing the gases they wish to include. 

Mixing ratios must be provided for gases included in one of two ways.

The simple way is to specify a constant value for all time in the 
integration.

The complex method is the one that can be used for CO2 etc and is described
best by the following example.

%I gas_rates




