The Mail-ID is used for various options in a run. Mail is sent to
this address and you should give a suitable form to allow the mail to
reach your local mail reader.  Form hadmk@hc0100 is preferred at UKMET.

The following options will send mail to this address:

   Error output from the archiving system (from the GPCS at UKMET).

   Job-finished message (from target machine,. At UKMET, this cannot
   cope with internet address).

You can set or unset these on various windows.
The mail address format need to agree with requirements of
all requested services.

