The start date is used to check that the start dump agrees with the
date expected by the user. Setting a date of
Year=Month=Day=hour=Min=Sec=0 disables the checks for runs that
include an assimilation in all circumstances.

Runs will fail if the start date does not match the date in the start
dump. However, the year of the dump can be changed to the same year as
the start date in the reconfiguration by selecting to "Override year
in dump with year in model basis time".

A value of Year=Month=Day=hour=Min=Sec=0 is set automatically
when using the generalised Suite Control System (SCS).

