#==============================================================================
# RCS Header:
#   File         [$Source: /home/hc0300/umui/srce_code/GHUI_archive/ghui2.0/Install/Makefile,v $]
#   Revision     [$Revision: 1.3 $]     Named [$Name: head#main $]
#   Last checkin [$Date: 2000/12/11 18:46:48 $]
#   Author       [$Author: hadsm $]
#==============================================================================
# This Makefile couples to the Makefile created by the Configure script
# thus saving the installer from having to remember to cd into the
# directory above before running make.

all:
	cd ..; $(MAKE)

install:
	cd ..; $(MAKE) install

clean:
	cd ..; $(MAKE) clean

distclean:
	cd ..; $(MAKE) distclean
