# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded GHUITable 1.0 [list source [file join $dir tableHeadings.tcl]]\n[list source [file join $dir tableMain.tcl]]\n[list source [file join $dir tableMethods.tcl]]
package ifneeded plb 1.0 [list source [file join $dir mplb.tcl]]
package ifneeded GHUI_process 1.1 [list load [file join $dir GHUI_process.sl]]
package ifneeded ghuiDatabase 1.1 [list load [file join $dir Ghuidatabase.sl]]
