#!/bin/ksh
%C---------------------------------------------------------------------
%C  File:  nds_submit
%C---------------------------------------------------------------------
%C
%C  Purpose: Generates SUBMIT, which creates compile, rcf and run 
%C           submission scripts
%C
%C  Include files:
%C   * nds_comp_switch     (Compile switch)
%C   * nds_run_switch      (Run switch)
%C   * nds_run_vars        (Submodel run switches)
%C   * nds_processor_usage (Processor breakdown)
%C   * nds_LoadLev_only    (LoadLeveler headers)
%C   * nds_Linux_only      (Linux headers)
%C   * nds_UserTable_only  ("Other" Machine headers, user defined table)
%C   * nds_Other_only      ("Other" Machine headers, empty)
%C---------------------------------------------------------------------
%C
#---------------------------------------------------------------------
# Name: SUBMIT
# Purpose: Creates umuisubmit_compile, umuisubmit_rcf 
#          and umuisubmit_run and any required wrapper scripts
#          on the remote platform. 
#         
# Created from UMUI vn%VERSION
#---------------------------------------------------------------------  

##########################################################
# Header common to all platforms                         #
##########################################################
export SHELL=/bin/ksh
. /etc/profile
%T if { %SUBMIT_METHOD == 6 } {
. /etc/bash.bashrc
%T }

SUBMITID=:::submitid:::                   
export SUBMITID    
RUNID=%RUN_ID
JOBDIR=$HOME/umui_runs/$RUNID-$SUBMITID
export JOBDIR
TYPE=%TCL put [if_active NCRUN %NCRUN NRUN] %ENDTCL	
CJOBN=%TCL putl [conv_RUNID %CJOBN] %ENDTCL

RHOST_NAME=%MACH_NAME
echo -e "\nYour job directory on host $RHOST_NAME is: $JOBDIR\n"

[ "$UMDIR" ] || . $HOME/.profile

###################################################
# Get date-time stamp for output files            #
# and set output class                            #
###################################################

OUTPUT_D=`date +%%y%%j`
OUTPUT_T=`date +%%H%%M%%S`
OCO=leave

%T if {%MYOUTPUT_OPT=="Y"} {
export MY_OUTPUT=%MYOUTPUT_VAL
%T } else {
export MY_OUTPUT=${MY_OUTPUT:-$HOME/output}
%T }
if ! test -d "$MY_OUTPUT"; then
   echo "Creating directory $MY_OUTPUT"
   mkdir -p $MY_OUTPUT
fi
COMP_OUT_PATH=$MY_OUTPUT
TARGET_OUT_PATH=$MY_OUTPUT

COMP_OUTFILE=$CJOBN.$RUNID.d$OUTPUT_D.t$OUTPUT_T.comp.$OCO
RCF_OUTFILE=$CJOBN.$RUNID.d$OUTPUT_D.t$OUTPUT_T.rcf.$OCO
RUN_OUTFILE=$CJOBN.$RUNID.d$OUTPUT_D.t$OUTPUT_T.$OCO

COMP_OUTPUT_FILE=$COMP_OUT_PATH/$COMP_OUTFILE
RCF_OUTPUT_FILE=$TARGET_OUT_PATH/$RCF_OUTFILE
RUN_OUTPUT_FILE=$TARGET_OUT_PATH/$RUN_OUTFILE

####################################################
# Set RUN_COMPILE, RUN_MODEL  variables            #
# to appropriate file umuisubmit_[compile/run/rcf] #
####################################################

%T putl ". \$JOBDIR/COMP_SWITCHES"

%I nds_run_vars
%I nds_comp_switch
%I nds_run_switch

###################################################
# Indicates if new recon. execut. required        #
###################################################

export RCF_NEW_EXEC=%TCL replacep COMP_RCF Y true * false %ENDTCL 
if [[ $RCF_NEW_EXEC = "true" && $TYPE = "CRUN" ]]; then
    echo "You have selected a compilation step and  a continuation run CRUN."
    echo "This is not allowed. Please modify your UMUI settings."
    exit
fi

######################################################
# Define script names from which stage_1_scr will be #
# composed for different tasks: compilation, run or  #
# reconfiguration. Stage_2_scr will be embedded into #
# stage_1_scr, when all three tasks together have to #
# be performed                                       #
######################################################

comp_header=$JOBDIR/umuisubmit_compile_header
comp_script=$JOBDIR/umuisubmit_compile
rcf_header=$JOBDIR/umuisubmit_rcf_header
rcf_script=$JOBDIR/umuisubmit_rcf
run_header=$JOBDIR/umuisubmit_run_header
run_script=$JOBDIR/umuisubmit_run
stage_1_scr=$JOBDIR/stage_1_submit
stage_2_scr=$JOBDIR/stage_2_submit

###################################################
# Processor usage                                 #
###################################################

%I nds_processor_usage

%C Variables required for the specific platform      
%C ################################################  
%T if {%SUBMIT_METHOD == 3} {
%I nds_LoadLev_only
%T } elseif {%SUBMIT_METHOD == 6} {
%I nds_Qsub_only
%T } elseif {%SUBMIT_METHOD == 7} {
%I nds_Qsub_monsoon
%T } elseif {%SUBMIT_METHOD == 1} {
%I nds_Linux_only
%T } else {
%T   if {%LUSROTHER=="Y"} {
%I nds_UserTable_only  
%T   } else {
%I nds_Other_only  
%T   }
%T }
%C ################################################

###################################################
# Concatinate headers with  platform independent  #
# body scripts                                    #
###################################################

# Compilation ===================
  cat $comp_header >>$comp_script
  cat $JOBDIR/COMP_SWITCHES >>$comp_script
  cat $JOBDIR/FCM_BLD_COMMAND >>$comp_script

# Reconfiguration =============
  cat $rcf_header >>$rcf_script
  cat >>$rcf_script<<EOF
export RUN_ATMOS=false
export RCF_ATMOS=true
export RCF_NEW_EXEC=false
EOF

# Run =========================
  cat $run_header >>$run_script
  cat >>$run_script<<EOF
export RUN_ATMOS=true
export RCF_ATMOS=false
export RCF_NEW_EXEC=false
%T if {%SUBMIT_METHOD == 6 || %SUBMIT_METHOD == 7} {
export OMP_NUM_THREADS=$NTHREADS_PER_TASK
%T }
EOF

################################################### 
# Set up common variables used in NRUNs and CRUNs #
###################################################

cat >>$JOBDIR/umuisubmit_vars<<EOF

# Choose shell "set" options for  lower level scripts
export SETOPT=""          
export TYPE=$TYPE

# SCM switch
export SCM_ATMOS=%TCL replacep OCAAA 5 true * false %ENDTCL 

%T if {%SUBMIT_METHOD == 3} {
# Output file for run following compilation run.
export CJOBN=$CJOBN
%T }
export AUTO_RESUB=%JRESUB
export MY_OUTPUT=$MY_OUTPUT
export TARGET_MC=$TARGET_MC
export JOBDIR=$JOBDIR
export SUBMITID=$SUBMITID
export DONT_TIDY=false

# MPP time limits
export UM_NPES=$UM_NPES
export NPROC_MAX=$(($UM_NPES+$FLUME_IOS_NPROC))
%T if {%SUBMIT_METHOD == 6} {
export NTASKS_PER_NODE=$NTASKS_PER_NODE
export NTASKS_PER_NUMANODE=$NTASKS_PER_NUMANODE
export NTHREADS_PER_TASK=$NTHREADS_PER_TASK
%T }
%T   if {%CICE == "T"} {
export CICE_NPROC=$CICE_NPROC
%T   }
%T   if {%NEMO == "T"} {
export NEMO_NPROC=$NEMO_NPROC
export NEMO_IPROC=$NEMO_IPROC
export NEMO_JPROC=$NEMO_JPROC
%T     if {[inactive_var OASIS]==0 && %OASIS=="T"} {
export PRISM_NPROC=$PRISM_NPROC
%T     }
%T if {%OASIS=="T" && %OASISWHICH==4} {
export CPL_TASK_SPACING=$CPL_TASK_SPACING
%T }
%T   }
export FLUME_IOS_NPROC=$FLUME_IOS_NPROC
%T   if { %ATMOS=="T" } {
export UM_ATM_NPROCX=$NMPPE
export UM_ATM_NPROCY=$NMPPN
%T   } else {
export UM_ATM_NPROCX=UNSET
export UM_ATM_NPROCY=UNSET
%T   }

export UM_THREAD_LEVEL=%THRD_LVL 
export RCF_NPES=$RCF_NPES
export RCF_NPROCY=$RCF_NPROCY
export RCF_NPROCX=$RCF_NPROCX
EOF

###################################################
# Copy the above variables into run script        #
# and add the SCRIPT                              #
###################################################

  echo "export UMRUN_OUTPUT=$RUN_OUTPUT_FILE" >>$run_script
  cat $JOBDIR/umuisubmit_vars >> $run_script
  echo "# Flag to indicate fully coupled HadGEM3 run" >>$run_script
%T if {(%ATMOS=="T")&&(%NEMO=="T")&&(%CICE=="T")} {
  echo "export HADGEM3_COUPLED=true" >>$run_script
%T } else {
  echo "export HADGEM3_COUPLED=false" >>$run_script
%T }
  cat $JOBDIR/SCRIPT >>$run_script
  echo "exit \$RC" >>$run_script

###################################################
# Copy the above variables into rcf script        #
# and add the SCRIPT                              #
###################################################

  echo "export UMRUN_OUTPUT=$RCF_OUTPUT_FILE" >>$rcf_script
  cat $JOBDIR/umuisubmit_vars >> $rcf_script
  if [[ $RUN_MODEL = "true" ]]; then
    echo "export DONT_TIDY=true" >>$rcf_script
  else
    echo "export DONT_TIDY=false" >>$rcf_script 
  fi
  echo "export HADGEM3_COUPLED=false" >>$rcf_script
  cat $JOBDIR/SCRIPT >>$rcf_script
  echo "if test \$RC -ne 0; then" >>$rcf_script
  echo "exit \$RC" >>$rcf_script
  echo "fi" >>$rcf_script
    
###################################################
# Create a wrapper script and change permissions  #
###################################################

touch $stage_1_scr
chmod 755 $stage_1_scr
chmod 755 $comp_script
chmod 755 $rcf_script
chmod 755 $run_script

###################################################
# Compose stage_1_scr and stage_2_scr (if needed) #
###################################################

if [[ $RUN_COMPILE = "true" ]]; then
  # If true compile needs to be performed first by running script in stage 1.
  cat $comp_header >>$stage_1_scr
  cat <<EOF        >>$stage_1_scr
$comp_script $SUB_OUT_CMP
CC=\$?
EOF
  if [[ $RUN_RCF = "true" ]]; then
    # If true stage 2 is needed and rcf needs to be run as script inside stage 2.
    if [[ $RUN_MODEL = "true" ]]; then
      # If true rcf to be run as script in stage 2 and model needs to be
      # scheduled inside stage 2.
      cat <<EOF >>$stage_1_scr
if [ \$CC -eq 0 ]
then
  $SUB_CMD $stage_2_scr $SUB_OUT_RCF
fi
EOF
      cat $rcf_header >>$stage_2_scr
      cat <<EOF       >>$stage_2_scr
$rcf_script $SUB_OUT_RCF
CC=\$?
if [ \$CC -eq 0 ]
then
  $SUB_CMD $run_script $SUB_OUT_RUN
fi
EOF
      chmod 755 $stage_2_scr
    else
      # We are not running model so schedule rcf inside stage 1.
      cat <<EOF >>$stage_1_scr
if [ \$CC -eq 0 ]
then
  $SUB_CMD $rcf_script $SUB_OUT_RCF
fi
EOF
    fi
  elif [[ $RUN_MODEL = "true" ]]; then
    # We are not running rcf so schedule model run inside stage 1.
    cat <<EOF >>$stage_1_scr
if [ \$CC -eq 0 ]
then
  $SUB_CMD $run_script $SUB_OUT_RUN
fi
EOF
  fi
elif [[ $RUN_RCF = "true" ]]; then
  # We are not compiling but running rcf so run rcf as script in stage 1.
  cat $rcf_header >>$stage_1_scr
  cat <<EOF       >>$stage_1_scr
$rcf_script $SUB_OUT_RCF
CC=\$?
EOF
  if [[ $RUN_MODEL = "true" ]]; then
    # We are runing model and rcf but not compiling so schedule model in 
    # stage 1.
    cat <<EOF >>$stage_1_scr
if [ \$CC -eq 0 ]
then
  $SUB_CMD $run_script $SUB_OUT_RUN
fi
EOF
  fi
else
  # We are not compiling or running rcf so run model as script in stage 1.
  cat $run_header >>$stage_1_scr
  cat <<EOF       >>$stage_1_scr
$run_script $SUB_OUT_RUN
EOF
fi

rm $JOBDIR/umuisubmit_vars
rm $JOBDIR/umuisubmit_compile_header
rm $JOBDIR/umuisubmit_rcf_header
rm $JOBDIR/umuisubmit_run_header

%T if { %AUTOPP == "Y" && (%MACH_NAME == "xcml00" || %MACH_NAME == "xcml01") } {
%I archi_scr_xc40
%T }

# END OF FILE
